### ISSUE TITLE
database warning and no login as superuser after installation (docker)

### ISSUE THREAD

**Issue by crazy-to-bike** [open-wanderer/wanderer#675]
### What happened?

I installed wanderer using the docker-compose.yml provided. Creating an account in the webinterface works, but creating an superuser with
`exec -it db /pocketbase superuser upsert email@example.com myverysecurepassword`
is showing a database warning and login with the credencials fails although success message:

> WARN You are using modernc.org/sqlite v1.39.0 which differs from the expected and tested v1.38.2.
> Make sure to either manually update in your go.mod the dependency version to the expected one OR if you want to keep yours ensure that its indirect modernc.org/libc dependency has the same version as in the https://gitlab.com/cznic/sqlite/-/blob/master/go.mod, otherwise it could result in unexpected build or runtime errors.
> 
> Successfully saved superuser "email@example.com"!

Further Question: Why is a simple sqlite database used instead of powerful mySQL, mariaDB or postrgres?

### Version

v0.18.3

**Comment by slothful-vassal** [comment]
Hi,

the warning is related to a recent pocketbase upgrade and appears at each container start. Should be fixed in one of the next releases (see #657).
sqlite is used by pocketbase, which is the database used by wanderer.


Regards

**Comment by crazy-to-bike** [comment]
Thanks. And how to log in as superuser? That doesn't work although there is a success message for the creation of a superuser.

**Comment by slothful-vassal** [comment]
Could you describe the appearing issue in detail? How do you try to login as superuser? In docker compose, you have defined a PUBLIC_POCKETBASE_URL. You need to use this URL with and add /\_/ to enter the admin page of pocketbase. eg. db.mywanderer.com/\_/

**Comment by crazy-to-bike** [comment]
Ok, I didn't  figure out that the backend is a complete different service. But when I change 
`PUBLIC_POCKETBASE_URL: http://db:8090` to
`PUBLIC_POCKETBASE_URL: http://wanderer-backend.mydomain.de` There's an error 500 trying to load https://wanderer.mydomain.de

**Comment by crazy-to-bike** [comment]
The pocketbase backend is reachable when I change `ORIGIN: http://localhost:3000` in the db setion to
`ORIGIN: http://wanderer-backend.mydomain.de`
and although in the db section
```
ports:
      - "8090:8090"
```
to
```
ports:
      - "127.0.0.1:5800:8090"
```
But the login still doesn't work: Invalid login credentials.

Edit: It was the password. With an easier password it works.

**Comment by crazy-to-bike** [comment]
Now I can't create a new user or login to wanderer: Error creating user / Error at login

I guess there is no database connection between web and db.

**Comment by slothful-vassal** [comment]
You have read the [Manual](https://wanderer.to/run/installation/#installation-via-docker)? Origin has to be same in each relevant Container.

**Comment by crazy-to-bike** [comment]
Yes, but that doesn't work. Either I can't login to wander (when PUBLIC_POCKETBASE_URL is not http://db:8090) or I get service not available for the backend (when PUBLIC_POCKETBASE_URL is not http://wanderer-backend.mydomain.de and ORIGIN in the db section ist not http://localhost:3000)

**Comment by slothful-vassal** [comment]
Yes, sorry. Public_pocketbase_url should remain http://db:8090.  origin should be the url you use to reach the Wanderer instance (Website). But origin has to be the same in db and web container.

**Comment by crazy-to-bike** [comment]
Ok. I think I found the problem why I could only either login the wanderer frontend OR reach the pocketbase backend.
My external Port for db is not 8090, because it's alrealy used by another service. With
```
db;
  ports:
      - "8090:8090"
```
I couldn't reach the Backend from the Web, With
```
db:
  ports:
      - "5090:8090"
```
I couldn't log on the wanderer frontend. With both
```
db: 
  ports:
      - "8090:8090"
      - "3070:8090"
```
both works.
